name: Release 

on:
  push:
    tags:
      - '*'

jobs:
  build: 
    uses: ./.github/workflows/build_release.yml
    with:
      version: ${{ github.head_ref || github.ref_name }}
      relname: ${{ github.ref_name }}
      prerelease: true
